name: BattleMap
version: '${project.version}'
main: me.cyclingman.battlemap.BattleMap
api-version: 1.19
authors: [Cyclingman]
description: Team based pvp game modes
commands:
  saves:
    description: loader and saver
    usage: either /saves save or /saves load

  controlPoint:
    description: Create a new control point.
    usage: /<command> create [name] [radius] [captureTime] [mapNumber] OR /controlpoint modify name/radius/captureTime/mapNumber [value]
