name: BattleMap
version: '${project.version}'
main: me.cyclingman.battlemap.BattleMap
api-version: 1.19
authors: [Cyclingman]
description: Team based pvp game modes
commands:
  catalog:
    description: Modify catalog saves.
    usage: /<command> [create, save, load, delete, list] ...

  map:
    description: Modify maps within current catalog.
    usage: /<command> [create, delete, update, activate, deactivate, list, gamemodes, goto, join]

  feature:
    description: Modify features within a map.
    usage: /<command> [delete, list, goto]

  controlpoint:
    description: Create a new control point.
    usage: /<command> create