name: BattleMap
version: '${project.version}'
main: me.cyclingman.battlemap.BattleMap
api-version: 1.19
authors: [Cyclingman]
description: Team based pvp game modes
commands:
  catalog:
    description: Create, save, load, delete and show catalogs.
    usage: /<command> [create, save, load, delete, list] ...

  map:
    description: create, retrieve and remove maps from catalog
    usage: /<command> [create, delete, update, activate, deactivate, list, gamemodes, goto]

  feature:
    description: retrieve and remove features from a map
    usage: /<command> [delete, list, goto]



  controlpoint:
    description: Create a new control point.
    usage: /<command>

  teleport:
    description: tp to other world