name: BattleMap
version: '1.0-SNAPSHOT'
main: me.cyclingman.battlemap.BattleMap
api-version: 1.19
authors: [Cyclingman]
description: Team based pvp game modes
commands:
  catalog:
    description: loader and saver
    usage: either /saves save or /saves load

  controlpoint:
    description: Create a new control point.
    usage: /<command>

  mapfeature:
    description: retrieve and remove features from a map
    usage: /<command>

  map:
    description: create, retrieve and remove maps from catalog
    usage: /<command>
